### ISSUE TITLE
upside down in fbo

### ISSUE THREAD

**Issue by paul-ferragut** [andreasmuller/NoiseWorkshop#2]
I am trying to draw the instanced particles in a ofFbo and things are flipped upside down. I tried rotating cameras but without success I was wondering if there are any solution you would recommend.

thank you for sharing this workshop all the example are great!

**Comment by andreasmuller** [comment]
Hi!

Hmm, try either or both of putting an ofScale(1,-1,1) after camera.begin() and changing 
https://github.com/andreasmuller/NoiseWorkshop/blob/master/ParticleSystemInstancedGPU/src/ParticleSystemInstancedGeometryGPU.cpp#L190

_shader->setUniformMatrix4f("u_modelViewMatrix", _camera->getModelViewMatrix() ); 

to

_shader->setUniformMatrix4f("u_modelViewMatrix", ofGetCurrentMatrix(OF_MATRIX_MODELVIEW) ); // (or something)

I'm sure I had a good reason to pass in the matrices myself at some point, but you're probably better off just reading the default ones that OF sets and use those.

**Comment by paul-ferragut** [comment]
Thank you so much for the hint!
ofScale(1,-1,1)
with _shader->setUniformMatrix4f("u_modelViewProjectionMatrix", ofGetCurrentMatrix(OF_MATRIX_MODELVIEW) *ofGetCurrentMatrix(OF_MATRIX_PROJECTION));
worked :)
